version: "3"
services:
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: nestapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
    - db-storage:/var/lib/postgresql/data

volumes:
  db-storage:
